// Code generated by protoc-gen-go. DO NOT EDIT.
// source: triplets.proto

/*
Package triplets is a generated protocol buffer package.

It is generated from these files:
	triplets.proto

It has these top-level messages:
	ChessBotTriplets
	ChessBotTriplet
	BoardBits
*/
package fetch

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChessBotTriplets struct {
	Triplets []*ChessBotTriplet `protobuf:"bytes,1,rep,name=triplets" json:"triplets,omitempty"`
}

func (m *ChessBotTriplets) Reset()                    { *m = ChessBotTriplets{} }
func (m *ChessBotTriplets) String() string            { return proto.CompactTextString(m) }
func (*ChessBotTriplets) ProtoMessage()               {}
func (*ChessBotTriplets) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChessBotTriplets) GetTriplets() []*ChessBotTriplet {
	if m != nil {
		return m.Triplets
	}
	return nil
}

type ChessBotTriplet struct {
	Parent   *BoardBits `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	Observed *BoardBits `protobuf:"bytes,2,opt,name=observed" json:"observed,omitempty"`
	Random   *BoardBits `protobuf:"bytes,3,opt,name=random" json:"random,omitempty"`
}

func (m *ChessBotTriplet) Reset()                    { *m = ChessBotTriplet{} }
func (m *ChessBotTriplet) String() string            { return proto.CompactTextString(m) }
func (*ChessBotTriplet) ProtoMessage()               {}
func (*ChessBotTriplet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChessBotTriplet) GetParent() *BoardBits {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *ChessBotTriplet) GetObserved() *BoardBits {
	if m != nil {
		return m.Observed
	}
	return nil
}

func (m *ChessBotTriplet) GetRandom() *BoardBits {
	if m != nil {
		return m.Random
	}
	return nil
}

type BoardBits struct {
	Pieces []uint32 `protobuf:"varint,1,rep,packed,name=pieces" json:"pieces,omitempty"`
}

func (m *BoardBits) Reset()                    { *m = BoardBits{} }
func (m *BoardBits) String() string            { return proto.CompactTextString(m) }
func (*BoardBits) ProtoMessage()               {}
func (*BoardBits) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BoardBits) GetPieces() []uint32 {
	if m != nil {
		return m.Pieces
	}
	return nil
}

func init() {
	proto.RegisterType((*ChessBotTriplets)(nil), "ChessBotTriplets")
	proto.RegisterType((*ChessBotTriplet)(nil), "ChessBotTriplet")
	proto.RegisterType((*BoardBits)(nil), "BoardBits")
}

func init() { proto.RegisterFile("triplets.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x29, 0xca, 0x2c,
	0xc8, 0x49, 0x2d, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x72, 0xe0, 0x12, 0x70, 0xce,
	0x48, 0x2d, 0x2e, 0x76, 0xca, 0x2f, 0x09, 0x81, 0xca, 0x08, 0xe9, 0x70, 0x71, 0xc0, 0x54, 0x49,
	0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0x09, 0xe8, 0xa1, 0x29, 0x0a, 0x82, 0xab, 0x50, 0x6a, 0x64,
	0xe4, 0xe2, 0x47, 0x93, 0x15, 0x52, 0xe2, 0x62, 0x2b, 0x48, 0x2c, 0x4a, 0xcd, 0x2b, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x36, 0xe2, 0xd2, 0x73, 0xca, 0x4f, 0x2c, 0x4a, 0x71, 0xca, 0x2c, 0x29,
	0x0e, 0x82, 0xca, 0x08, 0xa9, 0x71, 0x71, 0xe4, 0x27, 0x15, 0xa7, 0x16, 0x95, 0xa5, 0xa6, 0x48,
	0x30, 0x61, 0xa8, 0x82, 0xcb, 0x81, 0xcc, 0x2a, 0x4a, 0xcc, 0x4b, 0xc9, 0xcf, 0x95, 0x60, 0xc6,
	0x34, 0x0b, 0x22, 0xa3, 0xa4, 0xcc, 0xc5, 0x09, 0x17, 0x14, 0x12, 0xe3, 0x62, 0x2b, 0xc8, 0x4c,
	0x4d, 0x4e, 0x85, 0x38, 0x9e, 0x37, 0x08, 0xca, 0x4b, 0x62, 0x03, 0xfb, 0xd8, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0x66, 0x9c, 0x1c, 0xb4, 0x03, 0x01, 0x00, 0x00,
}
