# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: triplets.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='triplets.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0etriplets.proto\"6\n\x10\x43hessBotTriplets\x12\"\n\x08triplets\x18\x01 \x03(\x0b\x32\x10.ChessBotTriplet\"g\n\x0f\x43hessBotTriplet\x12\x1a\n\x06parent\x18\x01 \x01(\x0b\x32\n.BoardBits\x12\x1c\n\x08observed\x18\x02 \x01(\x0b\x32\n.BoardBits\x12\x1a\n\x06random\x18\x03 \x01(\x0b\x32\n.BoardBits\"\x1b\n\tBoardBits\x12\x0e\n\x06pieces\x18\x01 \x03(\rb\x06proto3')
)




_CHESSBOTTRIPLETS = _descriptor.Descriptor(
  name='ChessBotTriplets',
  full_name='ChessBotTriplets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='triplets', full_name='ChessBotTriplets.triplets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=72,
)


_CHESSBOTTRIPLET = _descriptor.Descriptor(
  name='ChessBotTriplet',
  full_name='ChessBotTriplet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='ChessBotTriplet.parent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='observed', full_name='ChessBotTriplet.observed', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='random', full_name='ChessBotTriplet.random', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=177,
)


_BOARDBITS = _descriptor.Descriptor(
  name='BoardBits',
  full_name='BoardBits',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pieces', full_name='BoardBits.pieces', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=206,
)

_CHESSBOTTRIPLETS.fields_by_name['triplets'].message_type = _CHESSBOTTRIPLET
_CHESSBOTTRIPLET.fields_by_name['parent'].message_type = _BOARDBITS
_CHESSBOTTRIPLET.fields_by_name['observed'].message_type = _BOARDBITS
_CHESSBOTTRIPLET.fields_by_name['random'].message_type = _BOARDBITS
DESCRIPTOR.message_types_by_name['ChessBotTriplets'] = _CHESSBOTTRIPLETS
DESCRIPTOR.message_types_by_name['ChessBotTriplet'] = _CHESSBOTTRIPLET
DESCRIPTOR.message_types_by_name['BoardBits'] = _BOARDBITS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChessBotTriplets = _reflection.GeneratedProtocolMessageType('ChessBotTriplets', (_message.Message,), dict(
  DESCRIPTOR = _CHESSBOTTRIPLETS,
  __module__ = 'triplets_pb2'
  # @@protoc_insertion_point(class_scope:ChessBotTriplets)
  ))
_sym_db.RegisterMessage(ChessBotTriplets)

ChessBotTriplet = _reflection.GeneratedProtocolMessageType('ChessBotTriplet', (_message.Message,), dict(
  DESCRIPTOR = _CHESSBOTTRIPLET,
  __module__ = 'triplets_pb2'
  # @@protoc_insertion_point(class_scope:ChessBotTriplet)
  ))
_sym_db.RegisterMessage(ChessBotTriplet)

BoardBits = _reflection.GeneratedProtocolMessageType('BoardBits', (_message.Message,), dict(
  DESCRIPTOR = _BOARDBITS,
  __module__ = 'triplets_pb2'
  # @@protoc_insertion_point(class_scope:BoardBits)
  ))
_sym_db.RegisterMessage(BoardBits)


# @@protoc_insertion_point(module_scope)
